### ISSUE TITLE
Backend preview issue when container is inside another container

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#511]
### Description
When a container is set to `Contained width` and is inside another container, it gets previewed as full width.

### Steps to reproduce
1. Create a container and add some padding and a background color.
2. Add another container inside it, add some padding and a background color. Set the container to `Contained width` and set the width to 400px.

#### Expected behavior
The container that has `Contained width` should preview with the assigned pixel value width.

#### Actual behavior
The container that has `Contained width` get previewed as if it was set to full width with an inner container of contained width. You can see that its background color extends to full width with a restricted inner container.

Tested with GP 3.2.0, GPP 2.2.0, GB 1.5.0 beta-2, GBPro 1.2.0, WP 6.0.

**Comment by tomusborne** [comment]
@quantumleap33 Can you try this with the current stable version of GP? I have a feeling it's a GP bug.

Thanks!

**Comment by quantumleap33** [comment]
@tomusborne Same issue with the stable version.

**Comment by tomusborne** [comment]
@quantumleap33 I believe this is fixed here now: https://github.com/tomusborne/generateblocks/pull/513

**Comment by quantumleap33** [comment]
@tomusborne Indeed, works as intended now, Tom, thanks!

**Comment by quantumleap33** [comment]
@tomusborne and @JeanPaiva 

I think there is still an issue with this.

Try and create two containers in a content template and set the container width to be equal to the container width set in the Customizer layout settings. The issue persists again. In fact, the size needs to be smaller than the difference between the layout container width set in the Customizer layout settings **minus** the sum of the left and right Container content paddings.

For example, if the container layout width is 1200px and the left and right container content paddings are 40px each, the issue will not persist up to 1120px. A value larger than 1120px will reveal the misalignment.

**Comment by tomusborne** [comment]
This is a bug in GP Premium. We'll be releasing GPP 2.1.3 around the same time as GB 1.5.0 to prevent this issue.
